services:

  wordpress:
    image: wordpress:latest
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser25
      WORDPRESS_DB_PASSWORD: 123Mudar
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wp_net
      - proxy-net
    volumes:
      - ./wp_data:/var/www/html
    deploy:
      replicas: 2 
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
      resources:
        limits:
          cpus: '1.0'
          memory: '1gb'

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser25
      MYSQL_PASSWORD: 123Mudar
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - wp_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '1.0'
          memory: '1gb'

volumes:
  db_data:
  wp_data:

networks:
  wp_net:
  proxy-net:
    driver: overlay